apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dev.yaml
  - stage.yaml
  - prod.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: cloud-native-devsecops
