apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: stage
    spec:
      containers:
        - name: shared-app
          env:
            - name: APP_ENV
              value: stage
