apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-secretsmanager
  target:
    name: prometheus-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cloud-native-devsecops/prod/monitoring/prometheus
        property: token
