name: Cloud-Native DevSecOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ACR_NAME: ${{ secrets.ACR_NAME }}

jobs:
  security-scans:
    name: Trivy + Checkov Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.sarif

      - name: Run Checkov IaC scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform-iac/
          framework: terraform
          output_format: sarif
          output_file_path: checkov.sarif

      - name: Upload Checkov results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-results
          path: checkov.sarif

  codeql-analysis:
    name: CodeQL Local Analysis (manual)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download CodeQL CLI
        run: |
          curl -LO https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip
          unzip codeql-linux64.zip
          ./codeql/codeql --version

      - name: Create CodeQL database
        run: |
          ./codeql/codeql database create codeql-db --language=javascript --source-root=.

      - name: Clone CodeQL JavaScript queries
        run: git clone https://github.com/github/codeql-javascript.git

      - name: Run CodeQL analysis
        run: |
          ./codeql/codeql database analyze codeql-db codeql-javascript/javascript-code-scanning.qls --format=sarifv2.1.0 --output=results.sarif

      - name: Upload CodeQL results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: results.sarif

  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    needs: [security-scans, codeql-analysis]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-iac

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform-iac

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform-iac

  build-and-push-image:
    name: Build and Push Container Image
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "ACR_LOGIN_SERVER=${{ secrets.ACR_NAME }}.azurecr.io" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/shared-app" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:master

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./shared-app
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
            org.opencontainers.image.title=shared-app
            org.opencontainers.image.description=Cloud Native DevSecOps Demo Application

  run-cost-analysis:
    name: Run Azure Cost Analysis
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Azure Cost Analyzer
        uses: ./cloud-cost-gpt
        with:
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload Cost Report
        uses: actions/upload-artifact@v4
        with:
          name: cost-report
          path: cost_report.md
