apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-secrets-store-inline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-secrets-store-inline
  template:
    metadata:
      labels:
        app: busybox-secrets-store-inline
    spec:
      containers:
      - name: busybox
        image: busybox
        command: [ "sleep", "3600" ]
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kv"
          nodePublishSecretRef:
            name: azure-secrets-store-creds